package presentacion.controlador;

public enum EventosControlador {
	
	// VISTA GENERAL
	VISTA_PRINCIPAL,
	
	// MODELO
	VISTA_MODELO,
	VISTA_ALTA_MODELO,
    ALTA_MODELO,
    BAJA_MODELO,
    CONSULTAR_MODELO_POR_ID,
    CONSULTAR_TODOS_MODELOS,
    MODIFICAR_MODELO,
    VINCULAR_MODELO,
    DESVINCULAR_MODELO,
    
    // AVIÓN
    VISTA_AVION,
    ALTA_AVION,
    BAJA_AVION,
    CONSULTAR_AVION_POR_ID,
    CONSULTAR_TODOS_AVIONES,
    MODIFICAR_AVION,
    MOSTRAR_AVIONES_POR_MODELO,
    MOSTRAR_AVIONES_POR_AEROLINEA,
    MOSTRAR_AVIONES_POR_HANGAR,
    
    // AEROLÍNEA
    VISTA_AEROLINEA,
    ALTA_AEROLINEA,
    BAJA_AEROLINEA,
    CONSULTAR_AEROLINEA_POR_ID,
    CONSULTAR_TODOS_AEROLINEAS,
    MODIFICAR_AEROLINEA,
    
    // CONTRATO
    VISTA_CONTRATO,
    ABRIR_CONTRATO,
    CERRAR_CONTRATO,
    BAJA_CONTRATO,
    ANYADIR_HANGAR_AL_CONTRATO,
    ELIMINAR_HANGAR_DEL_CONTRATO,
    CONSULTAR_CONTRATO_POR_ID,
    CONSULTAR_TODOS_CONTRATOS,
    MODIFICAR_CONTRATO,
    MODIFICAR_LINEA_CONTRATO,
    MOSTRAR_CONTRATOS_POR_AEROLINEA,
    
    // HANGAR
    VISTA_HANGAR,
    ALTA_HANGAR,
    BAJA_HANGAR,
    CONSULTAR_HANGAR_POR_ID,
    CONSULTAR_TODOS_HANGARES,
    MODIFICAR_HANGAR,
    
    // PERSONAL
    VISTA_PERSONAL,
    ALTA_PERSONAL,
    BAJA_PERSONAL,
    VINCULAR_PERSONAL,
    DESVINCULAR_PERSONAL,
    CONSULTAR_PERSONAL_POR_ID,
    CONSULTAR_PERSONAL_EXISTENTE,
    MODIFICAR_PERSONAL
}
